### ISSUE TITLE
mac按照步骤安装完docker启动不了

### ISSUE THREAD

**Issue by spirytuslove** [OpenGG/docker-tachidesk-chinese#1]
安装完docker启动了就终止然后又启动自己终止

**Comment by spirytuslove** [comment]
提示这个
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
/home/suwayomi/startup/startup_script.sh: 21: cannot create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied

**Comment by OpenGG** [comment]
@spirytuslove 
按照说明重新操作下

**Comment by spirytuslove** [comment]
> @spirytuslove 按照说明重新操作下

感谢 已经可以了 mac文件夹权限问题
